import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/page";
import Footer from "@/components/layout/Footer/page";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>

          {/* HEADER */}
          <Header />

          {/* CONTENT — WILL PUSH FOOTER DOWN */}
          <main className="flex-grow">
            {children}
          </main>

          {/* FOOTER */}
          <Footer />

        </Providers>
      </body>
    </html>
  );
}
